### ISSUE TITLE
Переменная для новых файлов

### ISSUE THREAD

**Issue by vasilevichra** [sergejey/majordomo-watchfolders#1]
Доброго дня!

Я хочу отправлять видео во vk/youtube, записанное с камеры.
Для этого подходит данный плагин, но в нём я не нашёл переменной или массива для добавленного файл(а|ов).

Как в данном примере `file`:

```sh
inotifywait -m $DIR -e create |
    while read path action file; do
        if [[ "$file" =~ .*avi$ ]]; then
            find $DIR -ctime +1 -delete
            sleep 30 && /home/pi/Scripts/shell/upload-video-youtube "${DIR}/${file}"
        fi
    done
```

Где взять переменную?

**Comment by sergejey** [comment]
Добрый день,

если задан вызов скрипта для каждого файла, то можно использовать переменную $params['FILENAME'], если же задан вызов по итогу проверки множества файлов, то массив $params['FILES_UPDATED']
